# Generated by Django 4.2.7 on 2023-11-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogginData',
            fields=[
                ('id', models.CharField(editable=False, max_length=250, primary_key=True, serialize=False)),
                ('email_phone', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('otp', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
